import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <section className="px-16">
          <nav className="px-8 py-4 flex items-center justify-center gap-3">
            <Link className="underline" href="/movies">Movies</Link>
            <Link className="underline" href="/actor">Actors</Link>
            <Link className="underline"  href="/director">Directors</Link>
          </nav>
        {children}
        </section>
        </body>
    </html>
  );
}
